import Head from "next/head";
import MainViewer from "@/components/common/MainViewer/MainViewer";
import { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>보리쌀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainViewer></MainViewer>
      </main>
    </>
  );
}
export default Home;
