import Head from "next/head";
import { Inter } from "next/font/google";
import MainViewer from "@/components/common/MainViewer/MainViewer";
import { NextPage } from "next";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  data: number;
}

const Home: NextPage<Props> = ({data}) => {
  return (
    <>
      <Head>
        <title>보리쌀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainViewer></MainViewer>
      </main>
    </>
  );
}
export default Home;

export async function getStaticProps() {
  const delayInSeconds = 2;
  const data = await new Promise((resolve) =>
    setTimeout(() => resolve(Math.random()), delayInSeconds * 1000)
  );

  return {
    props: { data },
    revalidate: 5 /** https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration */,
  };
}
